"""
Signal 1: Groq LLM Forensic Inspector.
Analyzes submitted content using Groq's high-speed inference API to evaluate
syntactic markers, cliché patterns, and prompt signatures, with graceful offline fallback.
"""

import os
import json
import logging
import re
from typing import Dict, Any
from groq import Groq

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are an expert digital forensics examiner specializing in provenance and attribution of creative writing (prose, poetry, essays, articles).
Analyze the provided text to determine whether it was authored by a human or generated by an AI language model.

Evaluate key AI indicators:
- Formulaic transitions (e.g., 'In conclusion', 'delve into', 'testament to', 'tapestry', 'furthermore', 'it is important to note')
- Unnatural syntactic symmetry and uniform clause balancing
- Overly polite, sterile, or emotionally detached tonal cadence
- Generic metaphors without idiosyncratic personal voice

Respond ONLY with valid JSON in this exact structure:
{
  "ai_probability": <float between 0.00 and 1.00, where 1.0 is definitely AI and 0.0 is definitely human>,
  "confidence": <float between 0.50 and 1.00 representing your certainty in this estimate>,
  "markers_detected": [<list of short strings describing detected signals>],
  "reasoning": "<concise analytical justification>"
}"""

class GroqDetector:
    def __init__(self, api_key: str = None, model: str = None, timeout: float = 10.0):
        self.api_key = api_key or os.getenv("GROQ_API_KEY", "")
        self.model = model or os.getenv("GROQ_MODEL", "qwen/qwen3.8-27b")
        self.timeout = timeout
        self.client = None
        if self.api_key:
            try:
                self.client = Groq(api_key=self.api_key)
            except Exception as e:
                logger.warning(f"Could not initialize Groq client: {e}")

    def analyze(self, text: str) -> Dict[str, Any]:
        """
        Analyze text using Groq LLM API.
        Falls back to offline heuristic analysis if API call fails or key is missing.
        """
        if not text or not text.strip():
            return {
                "score": 0.5,
                "confidence": 0.5,
                "model": self.model,
                "source": "empty_input",
                "markers": ["No content provided"],
                "reasoning": "Input text was empty or whitespace."
            }

        if self.client and self.api_key:
            try:
                # Sanitize text sample (limit to first 3000 chars for efficient inference)
                sample = text[:3000].strip()
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": f"Text to analyze:\n\n\"\"\"\n{sample}\n\"\"\""}
                    ],
                    temperature=0.1,
                    max_tokens=300,
                    response_format={"type": "json_object"}
                )

                content = response.choices[0].message.content
                parsed = json.loads(content)
                ai_prob = float(parsed.get("ai_probability", 0.5))
                # Bound between 0.0 and 1.0
                ai_prob = max(0.0, min(1.0, ai_prob))
                conf = float(parsed.get("confidence", 0.75))
                conf = max(0.5, min(1.0, conf))

                return {
                    "score": round(ai_prob, 4),
                    "confidence": round(conf, 4),
                    "model": self.model,
                    "source": "groq_api",
                    "markers": parsed.get("markers_detected", []),
                    "reasoning": parsed.get("reasoning", "LLM forensic evaluation completed.")
                }
            except Exception as e:
                logger.warning(f"Groq API call failed ({e}). Falling back to heuristic model.")

        # Offline fallback analyzer
        return self._offline_fallback(text)

    def _offline_fallback(self, text: str) -> Dict[str, Any]:
        """Heuristic offline analyzer used when Groq API is offline or unconfigured."""
        lower_text = text.lower()
        
        # Characteristic AI transition words and phrases
        ai_cliches = [
            "delve", "testament", "tapestry", "in conclusion", "it is important to note",
            "furthermore", "moreover", "beacon", "pivotal", "multifaceted",
            "vibrant tapestry", "crucial role", "serves as a", "not only", "in summary"
        ]
        
        found_cliches = [phrase for phrase in ai_cliches if phrase in lower_text]
        cliche_density = len(found_cliches) / (max(1, len(text.split())) / 100.0)
        
        # Estimate probability based on cliché density and structure
        base_score = 0.35  # default baseline
        if found_cliches:
            base_score += min(0.50, len(found_cliches) * 0.12)
        
        # Uniformity estimate
        sentences = [s.strip() for s in re.split(r'[.!?]+', text) if len(s.strip().split()) > 2]
        if sentences:
            lengths = [len(s.split()) for s in sentences]
            mean_len = sum(lengths) / len(lengths)
            variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
            if variance < 15 and len(sentences) > 3:
                base_score += 0.15  # Unusually uniform sentence rhythm
        
        final_score = max(0.05, min(0.95, base_score))
        return {
            "score": round(final_score, 4),
            "confidence": 0.70,
            "model": "offline_heuristic_fallback",
            "source": "heuristic_fallback",
            "markers": found_cliches,
            "reasoning": f"Analyzed using offline heuristic fallback; detected {len(found_cliches)} transitional patterns."
        }
