"""
Transparency label definitions and resolver for Provenance Guard.
Provides verbatim label texts for all three classification variants.
"""

# Verbatim Transparency Label Texts
LABEL_HIGH_CONFIDENCE_AI = (
    "AI-Generated Content: Our multi-signal analysis indicates with high confidence that this "
    "work was generated by an artificial intelligence model. Attributes such as uniform sentence "
    "cadences, characteristic language patterns, and syntactical markers strongly align with synthetic generation."
)

LABEL_HIGH_CONFIDENCE_HUMAN = (
    "Verified Human Creation: Our multi-signal analysis indicates with high confidence that this "
    "work is original human writing. Diverse vocabulary distribution, organic rhythm variations, "
    "and human stylistic nuances strongly align with authentic authorship."
)

LABEL_UNCERTAIN = (
    "Attribution Inconclusive: Our multi-signal analysis returned mixed or borderline indicators for "
    "this work. While certain stylistic features resemble automated generation, others suggest human "
    "composition or editing. Readers should evaluate this content with an awareness that attribution "
    "cannot be decisively determined."
)

LABEL_VARIANTS = {
    "high_confidence_ai": {
        "variant": "high_confidence_ai",
        "attribution": "ai",
        "display_name": "AI-Generated Content",
        "badge_color": "danger",
        "text": LABEL_HIGH_CONFIDENCE_AI
    },
    "high_confidence_human": {
        "variant": "high_confidence_human",
        "attribution": "human",
        "display_name": "Verified Human Creation",
        "badge_color": "success",
        "text": LABEL_HIGH_CONFIDENCE_HUMAN
    },
    "uncertain": {
        "variant": "uncertain",
        "attribution": "uncertain",
        "display_name": "Attribution Inconclusive",
        "badge_color": "warning",
        "text": LABEL_UNCERTAIN
    }
}

def resolve_transparency_label(variant_key: str) -> dict:
    """Retrieve full transparency label dictionary for a given variant key."""
    return LABEL_VARIANTS.get(variant_key, LABEL_VARIANTS["uncertain"])
